### ISSUE TITLE
请问一下你是通过什么方法解锁cfglock的，可以发下链接或者简要地说一下吗

### ISSUE THREAD

**Issue by WonWaylon** [bdragonh/T480S-BIGSUR-EFI#15]

**Comment by bdragonh** [comment]
https://github.com/crysehillmes/Hackintosh-Lenovo-M420-D046-C/blob/main/CFGLock.cn.md

**Comment by WonWaylon** [comment]
谢谢回复，已经解决不过使用的是这个方法https://bbs.pcbeta.com/viewthread-1868855-1-1.html

**Comment by bdragonh** [comment]
真能折腾 你有编程器 有夹子？
