### ISSUE TITLE
小红点问题

### ISSUE THREAD

**Issue by Yykai8899** [bdragonh/T480S-BIGSUR-EFI#20]
滚动屏幕上下滑是不会动的 左右滑小红点才会上下滚动屏幕 这个怎么回事呀 大佬求解决

**Comment by bdragonh** [comment]
估计改驱动VoodooRMI.kext中的参数   求解+1

**Comment by bdragonh** [comment]
使用 Bigsur_And_Monterey_2022_03_08 版本efi可以修复此问题

**Comment by Yykai8899** [comment]
> 使用 Bigsur_And_Monterey_2022_03_08 版本efi可以修复此问题

更新后是解决了 但是中键+小红点滚动页面时如果鼠标指针在链接上或者可交互的地方 会自动打开鼠标所在的页面

**Comment by bdragonh** [comment]
呵呵 , 鼠标中键按下本来就是可以打开超链接呀。  问题来了 你为什么非要在超链接上按下中键开始滚动?
