### ISSUE TITLE
USB定制的困惑？

### ISSUE THREAD

**Issue by yuan9jie** [bdragonh/T480S-BIGSUR-EFI#23]
你好，首先我是小白，使用你的EFI后，USB插U盘可以读盘，另外一块安装在电脑上的硬盘也能读取，但是摄像头无法驱动。我就定制了USB，定制USB后摄像头可以驱动了，但是电脑上的硬盘无法读取了（硬件SATA信息可以显示），U盘插入后也无法显示，军刀软件可以显示已插入。想问你知道这是啥情况吗？谢谢！而且自己定制USB后启动特别慢。。。你的EFI默认的USBPorts.kext启动就很快。还有个问题就是睡眠经常无法实现。谢谢

**Comment by yuan9jie** [comment]
> 你好，首先我是小白，使用你的EFI后，USB插U盘可以读盘，另外一块安装在电脑上的硬盘也能读取，但是摄像头无法驱动。我就定制了USB，定制USB后摄像头可以驱动了，但是电脑上的硬盘无法读取了（硬件SATA信息可以显示），U盘插入后也无法显示，军刀软件可以显示已插入。想问你知道这是啥情况吗？谢谢！而且自己定制USB后启动特别慢。。。你的EFI默认的USBPorts.kext启动就很快。还有个问题就是睡眠经常无法实现。谢谢

**Comment by sb0238** [comment]
你好，请问你的摄像头无法驱动解决了么，我也遇到了和你同样的问题。

**Comment by yuan9jie** [comment]
> 你好，请问你的摄像头无法驱动解决了么，我也遇到了和你同样的问题。

我有点记不清了，好像是重新定制了下USB接口就好了。你可以试一下

**Comment by sb0238** [comment]
你好，请问你现在还在用T480s黑苹果么，如果用的话，可以和我分享一下你定制的USB文件么；还有就是请教一下，你定制过USB后，触控板和小红点都可以正常使用么，谢谢。
