### ISSUE TITLE
电池“建议维修”

### ISSUE THREAD

**Issue by ives-66** [bdragonh/T480S-BIGSUR-EFI#6]
老哥晚上好，我利用你的EFI升级到monterey12.1，电池显示“建议维修”，不知道是我电池损坏还是驱动问题，请问你的电池状态正常吗？

**Comment by bdragonh** [comment]
我的为啥没事 难道还有兼容问题  你用时间机器退回去看一下

**Comment by ives-66** [comment]
没有做备份，没法退。我再观察观察，有可能是凑巧我电池坏了

**Comment by ives-66** [comment]
电池信息：

  型号信息：
  生产企业：	LGC
  设备名称：	01AV478
  Pack Lot Code：	0
  PCB Lot Code：	0
  固件版本：	0
  硬件校正：	0
  电池校正：	0
  电量信息：
  已充满电：	否
  正在充电：	是
  全负荷容量(mAh)：	2586
  充电状态(%)：	95
  效能信息：
  循环计数：	668
  状态：	建议维修

**Comment by bdragonh** [comment]
668次 也差不多了  电池最多设计使用次数也就1000次顶天了

**Comment by ives-66** [comment]
那应该是电池寿命到了，只能换了
